from .accessories     import *
from .cases           import *
from .contacts        import *
from .cooling         import *
from .disks           import *
from .headphones      import *
from .keyboards       import *
from .loyalty_program import *
from .monitors        import *
from .motherboards    import *
from .mousepads       import *
from .mouses          import *
from .order_cart      import *
from .power_units     import *
from .processors      import *
from .ram             import *
from .start_page      import *
from .video_cards     import *
